#!/usr/bin/env bash
set -euo pipefail

lb config noauto \
  --mode debian \
  --distribution trixie \
  --archive-areas "main contrib non-free non-free-firmware" \
  --architectures amd64 \
  --binary-images iso-hybrid \
  --bootappend-live "boot=live components quiet splash locales=en_US.UTF-8 keyboard-layouts=us timezone=UTC username=cdarzi hostname=cdarzi" \
  --debian-installer false \
  --firmware-chroot true \
  --firmware-binary true \
  --iso-application "cDarzi OS" \
  --iso-publisher "cDarzi Project" \
  --iso-volume "CDARZI_OS" \
  --memtest none \
  --security true \
  --updates true \
  --backports true
